### ISSUE TITLE
Parser Error: The identifier "Lua" isn't a valid type (not a script or class), or couldn't be found on base "self".

### ISSUE THREAD

**Issue by labolado** [backwardspy/kitchips#1]
<img width="234" alt="image" src="https://github.com/backwardspy/kitchips/assets/12539642/cc386f7a-f813-41e2-afad-4a9859a49e61">

Parser Error: The identifier "Lua" isn't a valid type (not a script or class), or couldn't be found on base "self".

**Comment by backwardspy** [comment]
hi, thanks for your interest in my project! i used a godot addon to add lua scripting support: https://github.com/WeaselGames/godot_luaAPI

specifically, the latest version 1 release should still work: https://github.com/WeaselGames/godot_luaAPI/releases/tag/v1.0-stable

i can't try this just yet, so please let me know if you get it working!

i would love to update this for godot 4 & luaAPI v2 at some point.

**Comment by backwardspy** [comment]
@labolado i've just hacked together some godot 4 support, and commented out the lua api stuff since it wasn't really being used yet anyway. the project should now run out of the box on the latest godot version!

**Comment by labolado** [comment]
It works now, thank you.
